### ISSUE TITLE
Supporting

### ISSUE THREAD

**Issue by etochesnok** [Kry9toN/KryPtoN-Music-Bot#1]
Add supporting many chat(bot connect to many group)

**Comment by Kry9toN** [comment]
Bot/User cannot join voice chat at the same time

**Comment by etochesnok** [comment]
> Bot/User cannot join voice chat at the same time

Can. I try to do it, and it can.

**Comment by Kry9toN** [comment]
> > Bot/User cannot join voice chat at the same time
> 
> Can. I try to do it, and it can.

how?

**Comment by etochesnok** [comment]
> > > Bot/User cannot join voice chat at the same time
> > 
> > 
> > Can. I try to do it, and it can.
> 
> how?

gcall1 = GroupCall(None, path_to_log_file='')
gcall2 = GroupCall(None, path_to_log_file='')
...

it's work, but it's bad code

**Comment by Kry9toN** [comment]
> > > > Bot/User cannot join voice chat at the same time
> > > 
> > > 
> > > Can. I try to do it, and it can.
> > 
> > 
> > how?
> 
> gcall1 = GroupCall(None, path_to_log_file='')
> gcall2 = GroupCall(None, path_to_log_file='')
> ...
> 
> it's work, but it's bad code

Yeah that bad code and hard to maintainer for long term
